# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
