version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pos_postgres
    restart: always
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pos_redis
    restart: always
    ports:
      - "6379:6379"

  process-order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process_order_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pos_db
      SPRING_DATASOURCE_USERNAME: pos_user
      SPRING_DATASOURCE_PASSWORD: pos_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://redis:6379" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
