server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: pos_user
    password: pos_password
    driver-class-name: org.postgresql.Driver
  application:
    name: pos-service
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
clients:
  shop-service:
    url: http://localhost:8080
  menu-service:
    url: http://localhost:8080
