server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: pos_user
    password: pos_password
    driver-class-name: org.postgresql.Driver
  application:
    name: pos-service
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  redisson:
    config:
      singleServerConfig:
        address: redis://localhost:6379
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
clients:
  shop-service:
    url: http://localhost:8080
  menu-service:
    url: http://localhost:8080

redisson:
  config:
    singleServerConfig:
      address: redis://localhost:6379
      connectionPoolSize: 64
      connectionMinimumIdleSize: 24
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      sslEnableEndpointIdentification: true
      sslProvider: JDK
      sslTruststore: null
      sslTruststorePassword: null
      sslKeystore: null
      sslKeystorePassword: null
      pingConnectionInterval: 1000
      keepAlive: false
      tcpNoDelay: false
      nameMapper: null
      addressResolverGroupFactory: null
